# Generated by Django 4.2.18 on 2025-01-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='initials',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
