# Generated by Django 4.2.18 on 2025-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_module_color_module_credits_module_initials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='curso',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
