# Generated by Django 4.2.18 on 2025-01-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_module_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='curso',
            new_name='course',
        ),
    ]
