# Generated by Django 4.2.18 on 2025-02-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_rename_curso_module_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='module',
            name='teacher',
        ),
    ]
