# Generated by Django 4.2.19 on 2025-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_remove_module_credits_remove_module_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
