# Generated by Django 4.2.11 on 2025-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1024)),
                ('fp_type', models.CharField(choices=[('BASICO', 'basico'), ('MEDIO', 'medio'), ('SUPERIOR', 'superior')], default='MEDIO', max_length=20)),
            ],
        ),
    ]
