# Generated by Django 4.2.18 on 2025-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp',
            name='code',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fp',
            name='short_name',
            field=models.CharField(default=34, max_length=10),
            preserve_default=False,
        ),
    ]
