# Generated by Django 4.2.18 on 2025-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0002_fp_code_fp_duration_fp_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fp',
            name='initials',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
