# Generated by Django 4.2.18 on 2025-01-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0003_fp_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fp',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
