# Generated by Django 4.2.18 on 2025-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0004_alter_fp_name_alter_fp_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='fp_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('SUPERIOR', 'SUPERIOR')], default='MEDIO', max_length=20),
        ),
    ]
