# Generated by Django 4.2.18 on 2025-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0005_alter_fp_fp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fp',
            name='fp_type',
            field=models.CharField(choices=[('BASICO', 'BASICO'), ('MEDIO', 'MEDIO'), ('SUPERIOR', 'SUPERIOR'), ('CURSO_ESPECIALIZACION', 'ESPECIALIZACION')], default='MEDIO', max_length=40),
        ),
    ]
