# Generated by Django 4.2.18 on 2025-02-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restart_password',
            field=models.BooleanField(default=True),
        ),
    ]
