# Generated by Django 4.2.18 on 2025-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='position',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
