# Generated by Django 4.2.19 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_remove_session_end_time_remove_session_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='week_day',
            field=models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('X', 'MIERCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES'), ('S', 'SABADO'), ('D', 'DOMINGO')], max_length=1),
        ),
    ]
