# Generated by Django 4.2.19 on 2025-02-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('session', '0003_alter_session_week_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='classroom.classroom'),
        ),
    ]
