# Generated by Django 4.2.18 on 2025-02-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='classsession',
            name='session',
            field=models.CharField(choices=[('S1', 'Session 1 (08:45-09:35)'), ('S2', 'Session 2 (09:35-10:25)'), ('S3', 'Session 3 (10:25-11:15)'), ('S4', 'Session 4 (11:15-12:05)'), ('S5', 'Session 5 (12:05-12:55)'), ('S6', 'Session 6 (12:55-13:45)'), ('S7', 'Session 7 (13:45-14:35)'), ('S8', 'Session 8 (16:00-16:50)'), ('S9', 'Session 9 (16:50-17:40)'), ('S10', 'Session 10 (17:40-18:30)'), ('S11', 'Session 11 (18:30-19:20)'), ('S12', 'Session 12 (19:20-20:10)'), ('S13', 'Session 13 (20:10-21:00)'), ('S14', 'Session 14 (21:00-21:50)'), ('S15', 'Session 15 (21:50-22:40)'), ('S16', 'Session 16 (22:40-23:30)')], default='S1', max_length=3),
            preserve_default=False,
        ),
    ]
