# Generated by Django 4.2.18 on 2025-02-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_remove_module_credits_remove_module_teacher'),
        ('schedule', '0002_remove_classsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('module', 'session', 'class_number')},
        ),
    ]
