# Generated by Django 4.2.18 on 2025-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_scheduleconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleconfig',
            old_name='end_time',
            new_name='afternoon_end_time',
        ),
        migrations.RenameField(
            model_name='scheduleconfig',
            old_name='start_time',
            new_name='afternoon_start_time',
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='morning_end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='morning_start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
