# Generated by Django 4.2.18 on 2025-02-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp', '0006_alter_fp_fp_type'),
        ('schedule', '0005_rename_end_time_scheduleconfig_afternoon_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_course', models.IntegerField()),
                ('fp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp.fp')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='afternoon_max_sessions',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='end_week_day',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='morning_max_sessions',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='schedule_type',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('MT', 'Mañana y Tarde')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='start_week_day',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='afternoon_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='morning_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.AddField(
            model_name='fpscheduleconfig',
            name='schedule_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduleconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='fpscheduleconfig',
            unique_together={('fp', 'schedule_config', 'fp_course')},
        ),
    ]
