# Generated by Django 4.2.18 on 2025-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_fpscheduleconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='afternoon_max_sessions',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='morning_max_sessions',
            field=models.IntegerField(default=6),
        ),
    ]
