# Generated by Django 4.2.18 on 2025-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_scheduleconfig_afternoon_max_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='afternoon_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='morning_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
