# Generated by Django 4.2.19 on 2025-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_scheduleconfig_afternoon_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='afternoon_max_sessions',
            field=models.IntegerField(default=6, null=True),
        ),
    ]
