# Generated by Django 4.2.19 on 2025-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_scheduleconfig_afternoon_max_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='end_week_day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='start_week_day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=1),
        ),
    ]
