# Generated by Django 4.2.19 on 2025-02-12 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_scheduleconfig_end_week_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
