# Generated by Django 4.2.19 on 2025-02-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_scheduleconfig_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleconfig',
            name='name',
        ),
    ]
