# Generated by Django 4.2.19 on 2025-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_scheduleconfig_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
