# Generated by Django 4.2.19 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_scheduleconfig_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfig',
            name='end_week_day',
            field=models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('X', 'MIERCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES'), ('S', 'SABADO'), ('D', 'DOMINGO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scheduleconfig',
            name='start_week_day',
            field=models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('X', 'MIERCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES'), ('S', 'SABADO'), ('D', 'DOMINGO')], max_length=1),
        ),
    ]
