# Generated by Django 4.2.18 on 2025-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_remove_module_credits_remove_module_teacher'),
        ('teacher', '0002_teachermodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='modules',
            field=models.ManyToManyField(related_name='teachers', through='teacher.TeacherModule', to='module.module'),
        ),
    ]
